# ==========================================
# Makefile - Taller de procesos            
# Autores: Thomas Leal, Carolina Ujueta
# Archivos: main.c, funciones.c, funciones.h
# ==========================================

# Nombre del ejecutable
TARGET = programa

# Archivos fuente
SRC = main.c funciones.c

$(TARGET):
	gcc $(SRC) -o $(TARGET)

clean:
	rm -f $(TARGET)

# ------------------------------------------
# Comandos útiles:
#   make        → compila el programa
#   make clean  → borra el ejecutable
# ------------------------------------------
